Repository marcosdosea/CoAuto, pull requests merged in 2023-09, with the labels that each got.

#102 Adicionar referencias dos protótipos nas descrições dos casos de uso. Closed #93
  Requisitos/CSU01 - Alugar Veiculo.docx
  Requisitos/CSU02 - Manter Avaliação Proprietário.docx
  Requisitos/CSU03 - Manter Avaliação Cliente.docx
  Requisitos/CSU04 - Manter Usuario.docx
  Requisitos/CSU09 - Autenticar usuário.docx
  Requisitos/CSU10 - Autorizar Veiculo.docx
  Requisitos/CSU11 - Disponibilizar Veiculo.docx
  Requisitos/CSU12 - Autorizar Pessoa.docx
Labels: documentation

#106 Correção do DER e do Banco de Dados juntamente ao Professor
  AnaliseProjeto/AnaliseProjeto.mdj
  AnaliseProjeto/DBCoAuto.mwb
  AnaliseProjeto/DBCoAuto.mwb.bak
  AnaliseProjeto/Entrega_veiculo.mwb.bak
Labels: documentation

#107 Adição da disponibilidade aos Prototipos/Tela - 7 e Tela - 21 [CLOSED 104]
  Requisitos/Prototipos/Tela - 21.png
  Requisitos/Prototipos/Tela - 4.png
  Requisitos/Prototipos/Tela - 7.png
Labels: documentation

#108 Inserido as referências aos protótipos dos Casos de uso: CSU04 - Mant…
  Requisitos/CSU04 - Manter Usuario.docx
  Requisitos/CSU06 - Realizar Devolução.docx
  Requisitos/CSU07 - Realizar Entrega.docx
  Requisitos/CSU08 - Realizar pagamento.docx
Labels: documentation

#143 Implementação do caso de uso Autorizar Veículo [CLOSED #117]
  Codigo/CoAutoWeb/.vs/CoAutoWeb/DesignTimeBuild/.dtbcache.v2
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/0995a99f-dc8a-476e-8457-3fea34d145c1.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/449ee0c9-1800-4633-9874-903d44aa9709.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/c723891c-e1d9-4e27-9d07-daa9e1ea5cc4.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/d71a1880-6423-4da1-8970-ba503ac97344.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/read.lock
  Codigo/CoAutoWeb/.vs/CoAutoWeb/v17/.futdcache.v2
  Codigo/CoAutoWeb/.vs/CoAutoWeb/v17/.suo
  Codigo/CoAutoWeb/.vs/ProjectEvaluation/coautoweb.metadata.v7.bin
  Codigo/CoAutoWeb/.vs/ProjectEvaluation/coautoweb.projects.v7.bin
  Codigo/CoAutoWeb/CoAutoWeb/obj/CoAutoWeb.csproj.nuget.dgspec.json
  Codigo/CoAutoWeb/CoAutoWeb/obj/CoAutoWeb.csproj.nuget.g.props
  Codigo/CoAutoWeb/CoAutoWeb/obj/CoAutoWeb.csproj.nuget.g.targets
  Codigo/CoAutoWeb/CoAutoWeb/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
  Codigo/CoAutoWeb/CoAutoWeb/obj/Debug/net6.0/CoAutoWeb.AssemblyInfo.cs
  Codigo/CoAutoWeb/CoAutoWeb/obj/Debug/net6.0/CoAutoWeb.AssemblyInfoInputs.cache
  Codigo/CoAutoWeb/CoAutoWeb/obj/Debug/net6.0/CoAutoWeb.GeneratedMSBuildEditorConfig.editorconfig
  Codigo/CoAutoWeb/CoAutoWeb/obj/Debug/net6.0/CoAutoWeb.GlobalUsings.g.cs
  Codigo/CoAutoWeb/CoAutoWeb/obj/Debug/net6.0/CoAutoWeb.RazorAssemblyInfo.cache
  Codigo/CoAutoWeb/CoAutoWeb/obj/Debug/net6.0/CoAutoWeb.RazorAssemblyInfo.cs
  Codigo/CoAutoWeb/CoAutoWeb/obj/Debug/net6.0/CoAutoWeb.assets.cache
  Codigo/CoAutoWeb/CoAutoWeb/obj/Debug/net6.0/CoAutoWeb.csproj.AssemblyReference.cache
  Codigo/CoAutoWeb/CoAutoWeb/obj/project.assets.json
  Codigo/CoAutoWeb/CoAutoWeb/obj/project.nuget.cache
Labels: enhancement

#144 Implementação do caso de uso manter veículo
  AnaliseProjeto/Entrega_veiculo.mwb.bak
  Codigo/CoAutoWeb/CoAutoWeb/CoAutoWeb.csproj
  Codigo/CoAutoWeb/CoAutoWeb/CoAutoWeb.csproj.user
  Codigo/CoAutoWeb/CoAutoWeb/Controllers/VeiculoController.cs
  Codigo/CoAutoWeb/CoAutoWeb/Mappers/VeiculoProfile.cs
  Codigo/CoAutoWeb/CoAutoWeb/Models/VeiculoViewModel.cs
  Codigo/CoAutoWeb/CoAutoWeb/Program.cs
  Codigo/CoAutoWeb/CoAutoWeb/Views/Veiculo/Create.cshtml
  Codigo/CoAutoWeb/CoAutoWeb/Views/Veiculo/Delete.cshtml
  Codigo/CoAutoWeb/CoAutoWeb/Views/Veiculo/Details.cshtml
  Codigo/CoAutoWeb/CoAutoWeb/Views/Veiculo/Edit.cshtml
  Codigo/CoAutoWeb/CoAutoWeb/Views/Veiculo/Index.cshtml
  Codigo/CoAutoWeb/CoAutoWeb/appsettings.json
  Codigo/CoAutoWeb/Core/CoAutoContext.cs
  Codigo/CoAutoWeb/Core/Core.csproj
  Codigo/CoAutoWeb/Core/DTO/VeiculoDTO.cs
  Codigo/CoAutoWeb/Core/Service/IVeiculoService.cs
  Codigo/CoAutoWeb/Service/Service.csproj
  Codigo/CoAutoWeb/Service/VeiculoService.cs
  Requisitos/Prototipos/Tela - 21.png
  Requisitos/Prototipos/Tela - 7.png
Labels: enhancement

#146 Implementado classe de serviço referentes ao caso de uso Alugar Veiculo.
  .vs/slnx.sqlite
  Codigo/CoAutoWeb/.vs/CoAutoWeb/DesignTimeBuild/.dtbcache.v2
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/3748f15b-6c03-446d-a132-91fe9b07f7fa.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/3aed945f-6c13-4647-b6b3-c41c5092b50d.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/712b5d12-95db-438f-a25b-20523fea6da2.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/db7e5b8c-9d3a-462d-b66c-c581b9590606.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/read.lock
  Codigo/CoAutoWeb/.vs/CoAutoWeb/config/applicationhost.config
  Codigo/CoAutoWeb/.vs/CoAutoWeb/v17/.futdcache.v2
  Codigo/CoAutoWeb/.vs/CoAutoWeb/v17/.suo
  Codigo/CoAutoWeb/.vs/ProjectEvaluation/coautoweb.metadata.v7.bin
  Codigo/CoAutoWeb/.vs/ProjectEvaluation/coautoweb.projects.v7.bin
  Codigo/CoAutoWeb/CoAutoWeb/Models/AluguelViewModel.cs
  Codigo/CoAutoWeb/Core/DTO/AluguelDTO.cs
  Codigo/CoAutoWeb/Core/Service/IAluguelService.cs
  Codigo/CoAutoWeb/Core/bin/Debug/net6.0/Core.deps.json
  Codigo/CoAutoWeb/Core/bin/Debug/net6.0/Core.dll
  Codigo/CoAutoWeb/Core/bin/Debug/net6.0/Core.pdb
  Codigo/CoAutoWeb/Core/bin/Debug/net6.0/Core.runtimeconfig.json
  Codigo/CoAutoWeb/Core/obj/Core.csproj.EntityFrameworkCore.targets
  Codigo/CoAutoWeb/Core/obj/Core.csproj.nuget.dgspec.json
  Codigo/CoAutoWeb/Core/obj/Core.csproj.nuget.g.props
  Codigo/CoAutoWeb/Core/obj/Core.csproj.nuget.g.targets
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.AssemblyInfo.cs
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.AssemblyInfoInputs.cache
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.GeneratedMSBuildEditorConfig.editorconfig
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.GlobalUsings.g.cs
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.assets.cache
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.csproj.AssemblyReference.cache
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.csproj.CoreCompileInputs.cache
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.csproj.FileListAbsolute.txt
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.dll
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.genruntimeconfig.cache
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/Core.pdb
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/ref/Core.dll
  Codigo/CoAutoWeb/Core/obj/Debug/net6.0/refint/Core.dll
  Codigo/CoAutoWeb/Core/obj/project.assets.json
  Codigo/CoAutoWeb/Core/obj/project.nuget.cache
  Codigo/CoAutoWeb/Service/AluguelService.cs
  Codigo/CoAutoWeb/Service/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs
  Codigo/CoAutoWeb/Service/obj/Debug/net6.0/Service.AssemblyInfo.cs
  Codigo/CoAutoWeb/Service/obj/Debug/net6.0/Service.AssemblyInfoInputs.cache
  Codigo/CoAutoWeb/Service/obj/Debug/net6.0/Service.GeneratedMSBuildEditorConfig.editorconfig
  Codigo/CoAutoWeb/Service/obj/Debug/net6.0/Service.GlobalUsings.g.cs
  Codigo/CoAutoWeb/Service/obj/Debug/net6.0/Service.assets.cache
  Codigo/CoAutoWeb/Service/obj/Debug/net6.0/Service.csproj.AssemblyReference.cache
  Codigo/CoAutoWeb/Service/obj/Service.csproj.nuget.dgspec.json
  Codigo/CoAutoWeb/Service/obj/Service.csproj.nuget.g.props
  Codigo/CoAutoWeb/Service/obj/Service.csproj.nuget.g.targets
  Codigo/CoAutoWeb/Service/obj/project.assets.json
  Codigo/CoAutoWeb/Service/obj/project.nuget.cache
Labels: enhancement

#148 Adicionado aquivo .gitignore
  .gitattributes
  .gitignore
  Codigo/CoAutoWeb/.vs/CoAutoWeb/DesignTimeBuild/.dtbcache.v2
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/3748f15b-6c03-446d-a132-91fe9b07f7fa.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/3aed945f-6c13-4647-b6b3-c41c5092b50d.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/712b5d12-95db-438f-a25b-20523fea6da2.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/FileContentIndex/db7e5b8c-9d3a-462d-b66c-c581b9590606.vsidx
  Codigo/CoAutoWeb/.vs/CoAutoWeb/v17/.futdcache.v2
  Codigo/CoAutoWeb/.vs/CoAutoWeb/v17/.suo
  Codigo/CoAutoWeb/.vs/ProjectEvaluation/coautoweb.metadata.v7.bin
  Codigo/CoAutoWeb/.vs/ProjectEvaluation/coautoweb.projects.v7.bin
Labels: enhancement

#150 Resolvendo erro da string de conexão
  Codigo/CoAutoWeb/Core/BibliotecaContext.cs
  Codigo/CoAutoWeb/Core/CoAutoContext.cs
Labels: bug

#155 Correção de bug na geração da view do caso de uso manter veículo [CLOSED #154]
  Codigo/CoAuto/Core/Disponibilidade.cs
  Codigo/CoAuto/Core/Service/IDisponibilidadeService.cs
  Codigo/CoAuto/Core/Service/IVeiculoService.cs
  Codigo/CoAuto/Core/bin/Debug/net6.0/Core.dll
  Codigo/CoAuto/Core/bin/Debug/net6.0/Core.pdb
  Codigo/CoAuto/Core/obj/Core.csproj.nuget.dgspec.json
  Codigo/CoAuto/Core/obj/Core.csproj.nuget.g.props
  Codigo/CoAuto/Core/obj/Debug/net6.0/Core.GeneratedMSBuildEditorConfig.editorconfig
  Codigo/CoAuto/Core/obj/Debug/net6.0/Core.assets.cache
  Codigo/CoAuto/Core/obj/Debug/net6.0/Core.csproj.AssemblyReference.cache
  Codigo/CoAuto/Core/obj/Debug/net6.0/Core.csproj.CoreCompileInputs.cache
  Codigo/CoAuto/Core/obj/Debug/net6.0/Core.csproj.FileListAbsolute.txt
  Codigo/CoAuto/Core/obj/Debug/net6.0/Core.dll
  Codigo/CoAuto/Core/obj/Debug/net6.0/Core.genruntimeconfig.cache
  Codigo/CoAuto/Core/obj/Debug/net6.0/Core.pdb
  Codigo/CoAuto/Core/obj/Debug/net6.0/ref/Core.dll
  Codigo/CoAuto/Core/obj/Debug/net6.0/refint/Core.dll
  Codigo/CoAuto/Core/obj/project.assets.json
  Codigo/CoAuto/Core/obj/project.nuget.cache
Labels: bug, enhancement

#159 Implementado Model, Service, Controller e view do caso de uso Realiza…
  Codigo/CoAuto/.vs/CoAuto/DesignTimeBuild/.dtbcache.v2
  Codigo/CoAuto/.vs/CoAuto/FileContentIndex/read.lock
  Codigo/CoAuto/.vs/CoAuto/v17/.futdcache.v2
  Codigo/CoAuto/.vs/CoAuto/v17/.suo
  Codigo/CoAuto/.vs/ProjectEvaluation/coauto.metadata.v7.bin
  Codigo/CoAuto/.vs/ProjectEvaluation/coauto.projects.v7.bin
  Codigo/CoAuto/CoAutoWeb/Controllers/PagamentoController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/PagamentoProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/PagamentoViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Program.cs
  Codigo/CoAuto/CoAutoWeb/Views/Pagamento/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pagamento/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pagamento/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pagamento/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pagamento/Index.cshtml
  Codigo/CoAuto/Core/DTO/PagamentoDTO.cs
  Codigo/CoAuto/Core/Service/IPagamentoService.cs
  Codigo/CoAuto/Service/PagamentoService.cs
Labels: enhancement

#162 Correção de erro na View Create Veículo com SeedingService #160
  Codigo/CoAuto/CoAutoWeb/Controllers/VeiculoController.cs.BASE.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/VeiculoController.cs.LOCAL.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/VeiculoController.cs.REMOTE.cs
Labels: bug, documentation

#165 Implementação do Model, Service e Controller do caso de uso Marca#164
  Codigo/CoAuto/CoAutoWeb/Controllers/MarcaController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/MarcaProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/MarcaViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Program.cs
  Codigo/CoAuto/CoAutoWeb/Views/Marca/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Marca/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Marca/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Marca/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Marca/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Shared/_Layout.cshtml
  Codigo/CoAuto/Core/Service/IMarcaService.cs
  Codigo/CoAuto/Service/MarcaService.cs
Labels: documentation

#168 Correção de bug referente a Create Manter Veículo #167
  Codigo/CoAuto/CoAutoWeb/Controllers/MarcaController.cs
  Codigo/CoAuto/CoAutoWeb/Models/VeiculoViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Views/Marca/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Veiculo/Create.cshtml
Labels: bug, enhancement

#170 Implementação do Model, Service, Controller e View da Tabela Modelo CLOSED[#163]
  Codigo/CoAuto/CoAutoWeb/CoAutoWeb.csproj.user
  Codigo/CoAuto/CoAutoWeb/Controllers/ModeloController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/VeiculoController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/ModeloProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/ModeloViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/VeiculoViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Views/Modelo/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Modelo/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Modelo/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Modelo/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Modelo/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Veiculo/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Veiculo/Details.cshtml
  Codigo/CoAuto/Core/Aluguel.cs
  Codigo/CoAuto/Core/Banco.cs
  Codigo/CoAuto/Core/CoAutoContext.cs
  Codigo/CoAuto/Core/Devolucao.cs
  Codigo/CoAuto/Core/Disponibilidade.cs
  Codigo/CoAuto/Core/Entrega.cs
  Codigo/CoAuto/Core/Marca.cs
  Codigo/CoAuto/Core/Modelo.cs
  Codigo/CoAuto/Core/Pagamento.cs
  Codigo/CoAuto/Core/Pessoa.cs
  Codigo/CoAuto/Core/SeedingService.cs
  Codigo/CoAuto/Core/Service/IDisponibilidadeService.cs
  Codigo/CoAuto/Core/Service/IModeloService.cs
  Codigo/CoAuto/Core/Service/IPagamentoService.cs
  Codigo/CoAuto/Core/Service/IVeiculoService.cs
  Codigo/CoAuto/Core/Veiculo.cs
  Codigo/CoAuto/Service/ModeloService.cs
Labels: enhancement

#171 Implementação do Model, Service e Controller do caso de uso Manter Pe…
  Codigo/CoAuto/CoAutoWeb/Controllers/PessoaController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/PessoaProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/PessoaModel.cs
  Codigo/CoAuto/Core/DTO/PessoaDto.cs
  Codigo/CoAuto/Core/Service/IPessoaService.cs
  Codigo/CoAuto/Service/PessoaService.cs
Labels: enhancement

#172 Branch joauxx 132
  Codigo/CoAuto/CoAutoWeb/Program.cs
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Shared/_Layout.cshtml
Labels: enhancement

#173 Implementação do View do caso de uso Receber Veículo #137
  Codigo/CoAuto/CoAutoWeb/Controllers/EntregaController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/EntregaProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/EntregaViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/MarcaViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Program.cs
  Codigo/CoAuto/CoAutoWeb/Views/Entrega/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Entrega/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Entrega/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Entrega/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Entrega/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Shared/_Layout.cshtml
  Codigo/CoAuto/Core/CoAutoContext.cs
  Codigo/CoAuto/Core/Efmigrationshistory.cs
  Codigo/CoAuto/Core/Migrations/20230910163249_InitialCreate.Designer.cs
  Codigo/CoAuto/Core/Migrations/20230910163249_InitialCreate.cs
  Codigo/CoAuto/Core/Migrations/CoAutoContextModelSnapshot.cs
  Codigo/CoAuto/Core/SeedingService.cs
  Codigo/CoAuto/Core/Service/IEntregaService.cs
  Codigo/CoAuto/Service/EntregaService.cs
Labels: enhancement

#176 Correção de bug do atributo uint - Entrega e Devolução [CLOSED #175]
  Codigo/CoAuto/CoAutoWeb/Controllers/DevolucaoController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/EntregaController.cs
  Codigo/CoAuto/CoAutoWeb/Models/EntregaViewModel.cs
  Codigo/CoAuto/Core/Service/IDevolucaoService.cs
  Codigo/CoAuto/Core/Service/IEntregaService.cs
  Codigo/CoAuto/Service/DevolucaoService.cs
  Codigo/CoAuto/Service/EntregaService.cs
Labels: bug, enhancement

#178 Correção de erro Manter Pessoa #177
  Codigo/CoAuto/CoAutoWeb/Controllers/PessoaController.cs
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Index.cshtml
  Codigo/CoAuto/Core/Service/IPessoaService.cs
  Codigo/CoAuto/Service/PessoaService.cs
Labels: bug, documentation

#180 Corrigido delete e edit da classe Aluguel. Closed #179
  Codigo/CoAuto/CoAutoWeb/Controllers/AluguelController.cs
Labels: bug, enhancement

#198 Correção do Banco de Dados. Closed #197
  AnaliseProjeto/DBCoAuto.mwb
  AnaliseProjeto/DBCoAuto.mwb.bak
Labels: bug, documentation

#200 Correção dos tipos de variáveis após mudanças no Banco de Dados. Clos…
  Codigo/CoAuto/CoAutoWeb/Controllers/AluguelController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/MarcaController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/ModeloController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/PessoaController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/VeiculoController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/PessoaProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/AluguelViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/DisponibilidadeModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/ModeloViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/PagamentoViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/PessoaViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/VeiculoViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Views/Aluguel/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Aluguel/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Aluguel/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Aluguel/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Aluguel/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Modelo/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Modelo/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Modelo/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Pessoa/Index.cshtml
  Codigo/CoAuto/Core/Aluguel.cs
  Codigo/CoAuto/Core/Banco.cs
  Codigo/CoAuto/Core/CoAutoContext.cs
  Codigo/CoAuto/Core/Devolucao.cs
  Codigo/CoAuto/Core/Disponibilidade.cs
  Codigo/CoAuto/Core/Efmigrationshistory.cs
  Codigo/CoAuto/Core/Entrega.cs
  Codigo/CoAuto/Core/Marca.cs
  Codigo/CoAuto/Core/Modelo.cs
  Codigo/CoAuto/Core/Pagamento.cs
  Codigo/CoAuto/Core/Pessoa.cs
  Codigo/CoAuto/Core/SeedingService.cs
  Codigo/CoAuto/Core/Service/IAluguelService.cs
  Codigo/CoAuto/Core/Service/IMarcaService.cs
  Codigo/CoAuto/Core/Service/IModeloService.cs
  Codigo/CoAuto/Core/Service/IVeiculoService.cs
  Codigo/CoAuto/Core/Veiculo.cs
  Codigo/CoAuto/Service/AluguelService.cs
  Codigo/CoAuto/Service/MarcaService.cs
  Codigo/CoAuto/Service/ModeloService.cs
  Codigo/CoAuto/Service/VeiculoService.cs
Labels: bug, enhancement

#201 Refatorar o código [CLOSED#181]
  Codigo/CoAuto/CoAutoWeb/Controllers/DevolucaoController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/DisponibilidadeController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/EntregaController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/HomeController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/MarcaController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/ModeloController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/PagamentoController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/PessoaController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/VeiculoController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/AluguelProfilecs.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/DisponibilidadeProfile.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/EntregaProfile.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/MarcaProfile.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/ModeloProfile.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/PagamentoProfile.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/PessoaProfile.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/VeiculoProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/AluguelViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/DisponibilidadeModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/ErrorViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/ModeloViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/PagamentoViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/PessoaViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/VeiculoViewModel.cs
  Codigo/CoAuto/Core/Aluguel.cs
  Codigo/CoAuto/Core/Banco.cs
  Codigo/CoAuto/Core/CoAutoContext.cs
  Codigo/CoAuto/Core/Devolucao.cs
  Codigo/CoAuto/Core/Disponibilidade.cs
  Codigo/CoAuto/Core/Entrega.cs
  Codigo/CoAuto/Core/Marca.cs
  Codigo/CoAuto/Core/Migrations/20230910163249_InitialCreate.cs
  Codigo/CoAuto/Core/Modelo.cs
  Codigo/CoAuto/Core/Pagamento.cs
  Codigo/CoAuto/Core/Pessoa.cs
  Codigo/CoAuto/Core/SeedingService.cs
  Codigo/CoAuto/Core/Service/IDisponibilidadeService.cs
  Codigo/CoAuto/Core/Service/IPagamentoService.cs
  Codigo/CoAuto/Core/Veiculo.cs
  Codigo/CoAuto/Service/AluguelService.cs
  Codigo/CoAuto/Service/DisponibilidadeService.cs
  Codigo/CoAuto/Service/EntregaService.cs
  Codigo/CoAuto/Service/MarcaService.cs
  Codigo/CoAuto/Service/PagamentoService.cs
Labels: enhancement

#203 Mudanças no campos de int para uint closed#202
  Codigo/CoAuto/CoAutoWeb/Controllers/DisponibilidadeController.cs
  Codigo/CoAuto/CoAutoWeb/Properties/launchSettings.json
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Shared/_Layout.cshtml
  Codigo/CoAuto/CoAutoWeb/appsettings.json
  Codigo/CoAuto/Core/CoAutoContext.cs
  Codigo/CoAuto/Core/Service/IDisponibilidadeService.cs
  Codigo/CoAuto/Service/DisponibilidadeService.cs
Labels: enhancement

#205 Implementar o teste do service e da controller do caso de uso Manter Pessoa.
  .DS_Store
  .gitignore
  Codigo/CoAuto/CoAuto.sln
  Codigo/CoAuto/CoAutoWeb/Models/PessoaViewModel.cs
  Codigo/CoAuto/CoAutoWebTests/CoAutoWebTests.csproj
  Codigo/CoAuto/CoAutoWebTests/Controllers/PessoaControllerTests.cs
  Codigo/CoAuto/Core/Service/IPessoaService.cs
  Codigo/CoAuto/Service/PessoaService.cs
  Codigo/CoAuto/ServiceTests/PessoaServiceTests.cs
  Codigo/CoAuto/ServiceTests/ServiceTests.csproj
Labels: enhancement

#207 Criação do Atributo dataAutorizacao nas classes de teste. closed #188
  Codigo/CoAuto/CoAutoWebTests/Controllers/PessoaControllerTests.cs
  Codigo/CoAuto/ServiceTests/PessoaServiceTests.cs
Labels: enhancement

#209 Implementado classe Banco. Closed #208
  .gitattributes
  Codigo/CoAuto/CoAutoWeb/CoAutoWeb.csproj.user
  Codigo/CoAuto/CoAutoWeb/Controllers/BancoController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/AluguelProfile.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/BancoProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/BancoViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Program.cs
  Codigo/CoAuto/CoAutoWeb/Views/Banco/Create.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Banco/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Banco/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Banco/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Banco/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Shared/_Layout.cshtml
  Codigo/CoAuto/Core/Service/IBancoService.cs
  Codigo/CoAuto/Service/BancoService.cs
Labels: enhancement

#212 Remoção do método assíncrono das classes Banco e Aluguel. Closed #211
  Codigo/CoAuto/CoAutoWeb/Controllers/AluguelController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/BancoController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/AluguelProfile.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/BancoProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/AluguelViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/BancoViewModel.cs
  Codigo/CoAuto/Core/CoAutoContext.cs
  Codigo/CoAuto/Core/DTO/AluguelDTO.cs
  Codigo/CoAuto/Core/Service/IAluguelService.cs
  Codigo/CoAuto/Core/Service/IBancoService.cs
  Codigo/CoAuto/Service/AluguelService.cs
  Codigo/CoAuto/Service/BancoService.cs
  Codigo/CoAuto/Service/Service.csproj
Labels: bug, enhancement

#213 Implementado dos testes para a class Banco. Closed #185
  .gitignore
  Codigo/CoAuto/CoAutoWeb/Controllers/BancoController.cs
  Codigo/CoAuto/CoAutoWeb/Mappers/BancoProfile.cs
  Codigo/CoAuto/CoAutoWeb/Models/BancoViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Views/Aluguel/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Aluguel/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Aluguel/Edit.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Aluguel/Index.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Banco/Delete.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Banco/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Banco/Index.cshtml
  Codigo/CoAuto/CoAutoWebTests/CoAutoWebTests.csproj
  Codigo/CoAuto/CoAutoWebTests/Controllers/BancoControllerTests.cs
  Codigo/CoAuto/Core/DTO/BancoDTO.cs
  Codigo/CoAuto/Core/Service/IBancoService.cs
  Codigo/CoAuto/Service/BancoService.cs
  Codigo/CoAuto/ServiceTests/BancoSeviceTests.cs
Labels: enhancement

#218 Implementação teste unitários Closed #191
  Codigo/CoAuto/CoAutoWebTests/CoAutoWebTests.csproj
  Codigo/CoAuto/CoAutoWebTests/Controllers/DisponibilidadeControllerTests.cs
Labels: enhancement

#219 Implementado dos testes para a class Aluguel. Closed #210
  Codigo/CoAuto/CoAutoWeb/Controllers/AluguelController.cs
  Codigo/CoAuto/CoAutoWeb/Models/AluguelViewModel.cs
  Codigo/CoAuto/CoAutoWebTests/Controllers/AluguelControllerTests.cs
  Codigo/CoAuto/ServiceTests/AluguelServiceTests.cs
Labels: enhancement

#220 Implementação dos testes para a class Marca
  Codigo/CoAuto/CoAutoWeb/Controllers/DisponibilidadeController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/MarcaController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/ModeloController.cs
  Codigo/CoAuto/CoAutoWeb/Models/DisponibilidadeModel.cs
  Codigo/CoAuto/CoAutoWeb/Models/MarcaViewModel.cs
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Details.cshtml
  Codigo/CoAuto/CoAutoWeb/Views/Disponibilidade/Index.cshtml
  Codigo/CoAuto/CoAutoWebTests/Controllers/DisponibilidadeControllerTests.cs
  Codigo/CoAuto/CoAutoWebTests/Controllers/MarcaControllerTests.cs
  Codigo/CoAuto/Core/DTO/MarcaDTO.cs
  Codigo/CoAuto/Core/Service/IMarcaService.cs
  Codigo/CoAuto/Service/MarcaService.cs
  Codigo/CoAuto/ServiceTests/MarcaServiceTests.cs
Labels: enhancement

#221 Realizado tests nos service de PagamentoController e PagamentoService…
  Codigo/CoAuto/CoAutoWeb/Controllers/PagamentoController.cs
  Codigo/CoAuto/CoAutoWebTests/Controllers/PagamentoControllerTests.cs
  Codigo/CoAuto/Core/DTO/PagamentoDTO.cs
  Codigo/CoAuto/Core/Service/IPagamentoService.cs
  Codigo/CoAuto/Service/PagamentoService.cs
  Codigo/CoAuto/ServiceTests/PagamentoServiceTests.cs
Labels: enhancement

#223 Implementado dos testes para a class Modelo. Closed#184
  Codigo/CoAuto/CoAutoWeb/Controllers/ModeloController.cs
  Codigo/CoAuto/CoAutoWeb/Controllers/VeiculoController.cs
  Codigo/CoAuto/CoAutoWebTests/Controllers/ModeloControllerTests.cs
  Codigo/CoAuto/Core/DTO/ModeloDTO.cs
  Codigo/CoAuto/Core/Service/IModeloService.cs
  Codigo/CoAuto/Service/ModeloService.cs
  Codigo/CoAuto/ServiceTests/ModeloServiceTests.cs
Labels: enhancement
